Repository fugerit-org/fj-doc, pull requests merged in 2023-02, with the labels that each got.

#28 Patch/issue 9
  docgen/parameters.json
  docgen/release-notes.txt
  fj-doc-base-json/pom.xml
  fj-doc-base-yaml/pom.xml
  fj-doc-base/pom.xml
  fj-doc-freemarker/pom.xml
  fj-doc-lib-autodoc/pom.xml
  fj-doc-lib-simpletable/pom.xml
  fj-doc-mod-fop/pom.xml
  fj-doc-mod-opencsv/pom.xml
  fj-doc-mod-poi/pom.xml
  fj-doc-playground-quarkus/pom.xml
  fj-doc-sample/pom.xml
  fj-doc-val-core/pom.xml
  fj-doc-val-pdfbox/pom.xml
  fj-doc-val-poi/pom.xml
  fj-doc-val/pom.xml
  pom.xml
Labels: dependencies

#30 Feature/issue 29
  docgen/parameters.json
  docgen/release-notes.txt
  fj-doc-base-json/pom.xml
  fj-doc-base-yaml/pom.xml
  fj-doc-base/pom.xml
  fj-doc-freemarker/pom.xml
  fj-doc-lib-autodoc/pom.xml
  fj-doc-lib-simpletable/pom.xml
  fj-doc-mod-fop/pom.xml
  fj-doc-mod-opencsv/pom.xml
  fj-doc-mod-opencsv/src/main/java/org/fugerit/java/doc/mod/opencsv/OpenCSVTypeHandler.java
  fj-doc-mod-poi/pom.xml
  fj-doc-playground-quarkus/pom.xml
  fj-doc-sample/pom.xml
  fj-doc-sample/src/main/resources/sample_docs/junit_base/intro_01.json
  fj-doc-sample/src/main/resources/sample_docs/junit_base/intro_01.yaml
  fj-doc-val-core/pom.xml
  fj-doc-val-pdfbox/pom.xml
  fj-doc-val-poi/pom.xml
  fj-doc-val/pom.xml
  pom.xml
Labels: bug, enhancement

#32 Feature/issue 31 unsface
  docgen/parameters.json
  docgen/release-notes.txt
  fj-doc-base-json/pom.xml
  fj-doc-base-yaml/pom.xml
  fj-doc-base/pom.xml
  fj-doc-base/src/main/java/org/fugerit/java/doc/base/facade/DocHandlerFactory.java
  fj-doc-freemarker/pom.xml
  fj-doc-lib-autodoc/pom.xml
  fj-doc-lib-simpletable/pom.xml
  fj-doc-mod-fop/pom.xml
  fj-doc-mod-opencsv/pom.xml
  fj-doc-mod-poi/pom.xml
  fj-doc-playground-quarkus/pom.xml
  fj-doc-sample/pom.xml
  fj-doc-sample/src/main/resources/config/doc-handler-sample.xml
  fj-doc-sample/src/test/java/test/org/fugerit/java/doc/sample/config/TestDocHandlerFactory.java
  fj-doc-val-core/pom.xml
  fj-doc-val-pdfbox/pom.xml
  fj-doc-val-poi/pom.xml
  fj-doc-val/pom.xml
  pom.xml
Labels: enhancement
