Repository fugerit-org/fj-doc, pull requests merged in 2023-09, with the labels that each got.

#57 Disable access to external entities in XML parsing #56
  CHANGELOG.md
  fj-doc-base/src/main/java/org/fugerit/java/doc/base/xml/DocValidator.java
  fj-doc-base/src/main/java/org/fugerit/java/doc/base/xml/SAXUtils.java
  fj-doc-base/src/test/java/test/org/fugerit/java/doc/base/xml/ReaderFail.java
  fj-doc-base/src/test/java/test/org/fugerit/java/doc/base/xml/TestDocValidator.java
  fj-doc-base/src/test/java/test/org/fugerit/java/doc/base/xml/TestSAXUtils.java
  fj-doc-freemarker/src/main/java/org/fugerit/java/doc/freemarker/process/FreemarkerDocProcessConfigValidator.java
  fj-doc-freemarker/src/test/java/test/org/fugerit/java/doc/freemarker/process/ReaderFail.java
  fj-doc-freemarker/src/test/java/test/org/fugerit/java/doc/freemarker/process/TestFreemarkerDocProcessConfigValidator.java
  fj-doc-freemarker/src/test/resources/fj_doc_test/freemarker-doc-process_ko.xml
  fj-doc-sample/src/test/java/test/org/fugerit/java/doc/sample/format/TestPOI.java
Labels: bug

#60 hotfix 1.5.10
  .github/dependabot.yml
  CHANGELOG.md
  fj-doc-base-json/pom.xml
  fj-doc-base-yaml/pom.xml
  fj-doc-base/pom.xml
  fj-doc-bom-core/README.md
  fj-doc-bom-core/pom.xml
  fj-doc-bom-fop/README.md
  fj-doc-bom-fop/pom.xml
  fj-doc-bom/README.md
  fj-doc-bom/pom.xml
  fj-doc-freemarker/pom.xml
  fj-doc-lib-autodoc/pom.xml
  fj-doc-lib-simpletable-import/pom.xml
  fj-doc-lib-simpletable/pom.xml
  fj-doc-mod-fop/pom.xml
  fj-doc-mod-opencsv/pom.xml
  fj-doc-mod-poi/pom.xml
  fj-doc-mod-poi5/pom.xml
  fj-doc-playground-quarkus/pom.xml
  fj-doc-sample/pom.xml
  fj-doc-sample/src/test/java/test/org/fugerit/java/doc/sample/dev/TestItext2.java
  fj-doc-tool/pom.xml
  fj-doc-val-core/pom.xml
  fj-doc-val-pdfbox/pom.xml
  fj-doc-val-poi/pom.xml
  fj-doc-val/pom.xml
  pom.xml
Labels: bug

#66 FopConfigClassLoader (previously deprecated) (#61)
  CHANGELOG.md
  fj-doc-mod-fop/pom.xml
  fj-doc-mod-fop/src/main/java/org/fugerit/java/doc/mod/fop/PdfFopTypeHandler.java
  fj-doc-mod-fop/src/main/java/org/fugerit/java/doc/mod/fop/config/ClassLoaderResourceResolver.java
  fj-doc-mod-fop/src/main/java/org/fugerit/java/doc/mod/fop/config/FopConfigClassLoader.java
  fj-doc-mod-fop/src/test/java/test/org/fugerit/java/doc/mod/fop/TestPdfFopTypeHandler.java
  fj-doc-mod-fop/src/test/resources/config/test_config_err1.xml
  fj-doc-mod-fop/src/test/resources/config/test_config_err2.xml
  fj-doc-mod-fop/src/test/resources/config/test_config_ok.xml
  fj-doc-mod-fop/src/test/resources/fop-config.xml
  fj-doc-mod-fop/src/test/resources/log4j2.xml
  fj-doc-mod-fop/src/test/resources/sample/doc_test_01.xml
  fj-doc-mod-fop/src/test/resources/sample/doc_test_02_ko.xml
Labels: enhancement

#74 [3.0.8] - 2023-09-23
  .github/workflows/build_maven_compatibility.yml
  .github/workflows/build_maven_package.yml
  .github/workflows/sonarcloud-maven.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
  fj-doc-base-json/pom.xml
  fj-doc-base-yaml/pom.xml
  fj-doc-base/pom.xml
  fj-doc-freemarker/pom.xml
  fj-doc-lib-autodoc/pom.xml
  fj-doc-lib-simpletable-import/pom.xml
  fj-doc-lib-simpletable/pom.xml
  fj-doc-mod-fop/pom.xml
  fj-doc-mod-opencsv/pom.xml
  fj-doc-mod-poi/pom.xml
  fj-doc-playground-quarkus/pom.xml
  fj-doc-sample/pom.xml
  fj-doc-tool/pom.xml
  fj-doc-val-core/pom.xml
  fj-doc-val-pdfbox/pom.xml
  fj-doc-val-poi/pom.xml
  fj-doc-val/pom.xml
  pom.xml
Labels: bug, documentation, enhancement
